version: '3'

services:
  telegraf:
    image: telegraf:1.16
    restart: unless-stopped
    container_name: telegraf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    links:
      - influxdb
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
    networks:
      - tig

  influxdb:
    image: influxdb:1.8
    restart: unless-stopped
    container_name: influxdb
    volumes:
      - ./influxdb/data:/var/lib/influxdb
    ports:
      - "8086:8086"
    networks:
      - tig

  grafana:
    image: grafana/grafana:7.2.0
    restart: unless-stopped
    container_name: grafana
    user: "root"
    volumes:
      - ./grafana/data:/var/lib/grafana
    links:
      - influxdb
    networks:
      - tig
    ports:
      - 3000:3000

networks:
  tig:
    driver: bridge
